version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - lawly_db
    ports:
      - "5051:5051"
    volumes:
      - .:/app

networks:
  lawly_db:
    external: true