version: '3.9'

services:
  prod-web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - lawly_prod_db
    ports:
      - "5052:5051"
    volumes:
      - .:/app

networks:
  lawly_prod_db:
    external: true